### ISSUE TITLE
Remove extraneous files

### ISSUE THREAD

**Issue by zbrozek** [NilsMinor/Raspberry-Pi-3-Altium-Template#1]
There are several unnecessary folders under version control:
- History folder
- Project Logs for RPI GPIO BOARD folder
- __Previews folder
- RPI 3.PcbDoc.htm
- RPI GPIO BOARD.PrjPcbStructure
- Debug.log

These may be safely deleted to make the project tidier.

**Comment by NilsMinor** [comment]
Yes, the files were part of my project version control, nobody else need them.
You deleted the image file, i will rey-load them with new images.
