### ISSUE TITLE
Cutout for ribbon cable doesn't include inside-corner radii

### ISSUE THREAD

**Issue by zbrozek** [NilsMinor/Raspberry-Pi-3-Altium-Template#2]
A router can't cut a perfect corner. The cutout for the connector should have inside radii. I would typically use 2-3 millimeters.

It may also be a good idea to turn that notch into a "board cutout" object that can be more-easily deleted if a user doesn't want it.

**Comment by NilsMinor** [comment]
Yes you are right, didn't thought about the milling tool, the board was produces one time for a weather station and we had no problems, but I think your recommendation is a benefit.
