### ISSUE TITLE
Screw holes should have pads rather than keepouts

### ISSUE THREAD

**Issue by zbrozek** [NilsMinor/Raspberry-Pi-3-Altium-Template#3]
Keepouts are a weird construct in Altium. They don't usually do what you want or expect, so I recommend avoiding them. Since these holes are for mounting to a motherboard, it's reasonable to expect screws in them.

Pads on both sides ensure that there is no artwork that will interfere with the screw head or the standoff. I'd suggest 6 mm to match the Pi 3 itself.

**Comment by NilsMinor** [comment]
Never had problems using Keepouts for my screws, but your solutions sounds also ok to me :)
